name: vehicle_cockpit
description: Vehicle Cockpit demo project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flame: ^1.21.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  vehicle_sim:
    path: packages/vehicle_sim

dev_dependencies:
  bloc_test: ^9.1.7
  flame_test: ^1.17.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.6.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
